name: Deploy React to GitHub Pages

on:
  push:
    branches: ["main"]  # Runs this action when code is pushed to the main branch

permissions:
  contents: write # Required to push the build files to the gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Uses a current stable version of Node

      - name: Install dependencies
        run: npm install
        working-directory: ./Aura-Clinic

      - name: Build the project
        run: npm run build
        working-directory: ./Aura-Clinic

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: Aura-Clinic/build # The folder the build process generated
          branch: gh-pages # The branch the action should deploy to.
